name: auto_orientation
description: Set the device orientation programmatically for iOS and Android
version: 2.0.0
author: Sebastian Faujour <sf@bytepark.de>
homepage: https://github.com/bytepark/auto_orientation

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: de.bytepark.autoorientation
    pluginClass: AutoOrientationPlugin
