name: auto_orientation
description: Set the device orientation programmatically
version: 0.0.1
author: Sebastian Faujour <sf@bytepark.de>
homepage: https://www.bytepark.de

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: de.bytepark.autoorientation
    pluginClass: AutoOrientationPlugin
